### PR TITLE
Move treemap labels to inside of dir

### LINKED ISSUE #306: labels should be inside their rectangles
image

the labels for the treemap view are playing with my perception. i suspect that they violate the [gestalt law of common region](https://www.usertesting.com/blog/gestalt-principles#:~:text=The%20principle%20of%20common%20region,them%20as%20being%20grouped%20together.) maybe. that it's that law, or another, I think it would be better if they were inside the rectangle.

questions are: do you agree with me?  did you consider this and decided against it?

### PR DESCRIPTION
**Pull request by emiljapelt**
Resolves #306

### CODE REVIEW

**Review by joglr — APPROVED** [review]
Great chance! Compared it to main and it looks great!

**Review by joglr — CHANGES_REQUESTED** [review]
I would like these numbers to be defined in const

**Review by joglr — APPROVED** [review]
LGTM!

**Review by hojelse — APPROVED** [review]
Cool beans :rock:

**Pull request merged**
